version: 2.1


workflows:
  test-deploy:
    jobs:
      - build


# if there is only one job then it has to be named build
jobs:
  build:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - run: 
          name: Building image with docker
          command: docker build -t build -f Dockerfile.dev
      - run:
          name: Running Tests
          command: docker run build npm run test --  --coverage