orbs:
  docker: circleci/docker@2.2.0
version: 2.1


workflows:
  build-and-test:
    jobs:
      - build-image


# if there is only one job then it has to be named build
jobs:
  build-image:
    executor: docker/machine
    steps:
      - checkout
      - docker/build:
          image: temp-image
          dockerfile: Dockerfile.dev
          tag: temp-tag


