version: 2.1

jobs:
  build-image:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: |
            docker build -t temp-image -f Dockerfile.dev .
            mkdir -p ~/docker-image
            docker save temp-image -o ~/docker-image/temp-image.tar
            ls -lh ~/docker-image

  run-image:
    docker:
      - image: circleci/node:14
    steps:
      - attach_workspace:
          at: ~/docker-image
      - run:
          name: Load Docker image
          command: |
            docker load -i temp-image.tar
            docker images
      - run:
          name: Run Docker container
          command: |
            docker run --rm -p 8080:8080 temp-image

workflows:
  build-and-test:
    jobs:
      - build-image
      - run-image:
          requires:
            - build-image
